### ISSUE TITLE
The path to the source file will be copied

### ISSUE THREAD

**Issue by ijustlearn** [appleboy/scp-action#1]
example:
```  yaml
name: coupon-backend deploy
on: push

jobs:
  deloy:
    runs-on: ubuntu-latest
    steps:
uses: appleboy/scp-action@v0.0.1
        env:
          HOST: ${{ secrets.SSH_HOST }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USERNAME: ${{ secrets.SSH_USER }}
          SOURCE: target/${{ steps.setenv.outputs.JAR_FILE }}
          TARGET: /usr/coupon/
```
after action, cat file on server:
``` sh
[root@VM_0_8_centos coupon]# cd /usr/coupon/
[root@VM_0_8_centos coupon]# ls
keystore.p12  target
[root@VM_0_8_centos coupon]#ls target
coupon-0.0.1-SNAPSHOT.jar
```
so , the issues is：
The path to the source file will be copied。
Unlike executing the cp command on the host。

Thanks～

**Comment by appleboy** [comment]
remove the specified number of leading path elements

```yaml
- name: remove the specified number of leading path elements
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
    source: "tests/a.txt,tests/b.txt"
    target: "foobar"
    strip_components: 1
```

old target structure:

```sh
foobar
  └── tests
    ├── a.txt
    └── b.txt
```

new target structure:

```sh
foobar
  ├── a.txt
  └── b.txt
```
