### ISSUE TITLE
IO Timeout Regression since 2023-04-03

### ISSUE THREAD

**Issue by dcaslin** [appleboy/scp-action#106]
As of today Actions using https://github.com/dcaslin/d2-checklist/actions with 

`uses: appleboy/scp-action@master` 

Have been failing with an IO timeout after uploading the tarball (see https://github.com/dcaslin/d2-checklist/actions/runs/4652652207 for a live case)

```
tar all files into /tmp/AMsdjMEvbv.tar.gz
scp file to server.
create folder /home/***/d2checklist/
untar file AMsdjMEvbv.tar.gz
remove file AMsdjMEvbv.tar.gz
drone-scp error:  dial tcp ***:***: i/o timeout
drone-scp rollback: remove all target tmp file
remove file AMsdjMEvbv.tar.gz
2023/04/09 ***:04:05 dial tcp ***:***: i/o timeout
```

By pinning to a previous version 

`      uses: appleboy/scp-action@98930d398ce425af0148ea8a0e3295cd04fe2b7a`

The issue goes away

**Comment by appleboy** [comment]
Can you show your config and remove OS version?

**Comment by appleboy** [comment]
According to your config

```
Run appleboy/scp-action@master
  with:
    source: ./dist/
    target: /home/***/d[2](https://github.com/dcaslin/d2-checklist/actions/runs/4652652207/jobs/8233035792#step:11:2)checklist/
    strip_components: 2
    port: ***
    timeout: [3](https://github.com/dcaslin/d2-checklist/actions/runs/4652652207/jobs/8233035792#step:11:3)0s
    command_timeout: 10m
    use_insecure_cipher: false
    rm: false
    debug: false
    overwrite: false
    tar_dereference: false
    tar_exec: tar
    proxy_port: ***
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
  env:
    HOST: ***
    USERNAME: ***
    PORT: ***
    KEY: ***
```

**Comment by appleboy** [comment]
@dcaslin Can you help to try the two versions?

1. appleboy/scp-action@v0.1.3 (working?)
2. appleboy/scp-action@v0.1.4 (not working?)

Thanks.

**Comment by dcaslin** [comment]
![image](https://user-images.githubusercontent.com/16437968/230939339-6be2c753-8ea0-4daf-8669-9f73e26fb04a.png)

Confirmed, 0.1.3 works, 0.1.4 fails

**Comment by dcaslin** [comment]
Btw in terms of target OS:

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

**Comment by cacacaio** [comment]
I'm having the same issue, reverting my workflow to 0.1.3 works for now, but basically every workflow in my org is broken cause of this update, I'm hoping for a fix soon cause we have a lot of projects and changing every single one by hand kind of sucks.

**Comment by appleboy** [comment]
@cacacaio @dcaslin please help to try the following version

```diff
- appleboy/scp-action@v0.1.3
+ appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35
```

**Comment by appleboy** [comment]
You will see the following log

![image](https://user-images.githubusercontent.com/21979/231035714-ae082771-a1f9-48ca-b50b-333d09590525.png)

> remote server os type is uix

**Comment by appleboy** [comment]
@cacacaio Don't use the master version in your production.

**Comment by csalmeida** [comment]
I have the same issue pinning the package to version `appleboy/scp-action@98930d398ce425af0148ea8a0e3295cd04fe2b7a` fixed it. 

Thanks! 🙏

**Comment by appleboy** [comment]
@csalmeida You should try [v0.1.4](https://github.com/appleboy/scp-action/releases/tag/v0.1.4)

**Comment by dcaslin** [comment]
> @cacacaio @dcaslin please help to try the following version
> 
> ```diff
> - appleboy/scp-action@v0.1.3
> + appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35
> ```

Tested here: https://github.com/dcaslin/d2-checklist/actions/runs/4704329113/jobs/8343852155

**Comment by appleboy** [comment]
@dcaslin 

Find

```yaml
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.UID }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
      with:
        source: "./dist/"
        target: "/home/${{ secrets.UID }}/d2checklist/"
        strip_components: 2 # this is important
```

Change to 

```yaml
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.UID }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH }}
        source: "./dist/"
        target: "/home/${{ secrets.UID }}/d2checklist/"
        strip_components: 2 # this is important
```

Don't use `env` and please try the master branch `appleboy/scp-action@master`

**Comment by csalmeida** [comment]
> @csalmeida You should try [v0.1.4](https://github.com/appleboy/scp-action/releases/tag/v0.1.4)

Thanks @appleboy, will give that a go when I find a moment. 🙏

**Comment by alepiumetti** [comment]
> @dcaslin Can you help to try the two versions?
> 
> 1. appleboy/scp-action@v0.1.3 (working?)
> 2. appleboy/scp-action@v0.1.4 (not working?)
> 3. `appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35` (?)
> 
> Thanks.

i tried this. 
v0.1.3 working for me
v0.1.4 , `209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35` and `master` not

**Comment by martinmine** [comment]
Can confirm I also have the same issue on `scp-action@master`:

```
tar all files into /tmp/ksMjbzXtJD.tar.gz
remote server os type is unix
scp file to server.
create folder /var/www/itemsearch
untar file ksMjbzXtJD.tar.gz
drone-scp error:  dial tcp ***:***: i/o timeout
drone-scp rollback: remove all target tmp file
remove file ksMjbzXtJD.tar.gz
```

[Here](https://github.com/ProjectCeleste/celeste-search/blob/master/.github/workflows/build_prod.yml) is my pipeline yaml for reference.

v0.1.4 and master is broken for me. v0.1.3 is working fine.

**Comment by dev-subscriber-world** [comment]
The same issue for me on v0.1.4 and all works on v0.1.3.
Here is my pipeline:
```
- name: copy docker-compose via ssh key
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DROPLET_SSH_HOST }}
        username: ${{ secrets.DROPLET_SSH_USER }}
        port: 22
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "/subscriber-core"
```
