### ISSUE TITLE
Error "can't connect without a private SSH key or password"

### ISSUE THREAD

**Issue by saberkovich** [appleboy/scp-action#113]
I ran into the error I described in the title, tried to reinstall the server but nothing helps. Surprisingly, yesterday everything was working fine, today the error is already popping up.

My file:

```yml
name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/servers_folder/bfg-bot/"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: reboot
```

Error:

`Error: can't connect without a private SSH key or password`

**Comment by saberkovich** [comment]
I know that already wrote on this error, it was specified that you need to add:
`environment: main`
That didn't work.

**Comment by kherchel** [comment]
Switch from using scp-action@master to v0.1.4, this fixed the issue for me

**Comment by dongeerts** [comment]
I have the same issue when using the `@master` version. Using `@v0.1.4` as @kherchel mentioned fixes the issue for now.

**Comment by saberkovich** [comment]
Now I see another error:

`ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

**Comment by saberkovich** [comment]
> Switch from using scp-action@master to v0.1.4, this fixed the issue for me

This solution worked.

Note: Set version `v0.1.4` only in file transfer settings, no need in `Executing remote command`.

**Comment by appleboy** [comment]
@saberkovich Please update your config. Don't use environment variable.

Find

```yaml
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/servers_folder/bfg-bot/"
```

Replace

```yaml
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "/servers_folder/bfg-bot/"
```
