### ISSUE TITLE
tar all files into /tmp/aYVZpBGYPO.tar.gz tar: empty archive exit status 1

### ISSUE THREAD

**Issue by yavda1** [appleboy/scp-action#127]
Hi, I'm trying to use this with github actions to host a discord bot directly to my ubuntu server but im getting this error in the workflow

```
tar all files into /tmp/aYVZpBGYPO.tar.gz
tar: empty archive
exit status 1
```

this my cd.yml
```
name: FunkyBot CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          cd /discordBots/funkybot
          git pull origin main
          git status
          npm install --only=prod
          pm2 restart funkybot
```
this is my ci.yml
```
name: FunkyBot CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19
      uses: actions/setup-node@v2
      with:
        node-version: 19.x
    - run: npm i
<img width="1815" alt="Screen Shot 2023-06-06 at 5 15 40 PM" src="https://github.com/appleboy/scp-action/assets/94653933/044078c1-9b34-4ef8-bcc3-cc511f0310d1">

    - run: npm run build --if-present
    - run: npm test
  ```
if its related, im also getting this warning

```
Warning: Unexpected input(s) 'script', valid inputs are ['entryPoint', 'args', 'host', 'port', 'username', 'password', 'timeout', 'command_timeout', 'key', 'key_path', 'passphrase', 'fingerprint', 'use_insecure_cipher', 'target', 'source', 'rm', 'debug', 'strip_components', 'overwrite', 'tar_dereference', 'tar_tmp_path', 'tar_exec', 'proxy_host', 'proxy_port', 'proxy_username', 'proxy_password', 'proxy_passphrase', 'proxy_timeout', 'proxy_key', 'proxy_key_path', 'proxy_fingerprint', 'proxy_use_insecure_cipher']
```
