### ISSUE TITLE
Source folder created at target

### ISSUE THREAD

**Issue by cyberience** [appleboy/scp-action#133]
In the following example, the ./html folder is created at target, and doesnt matter how I structure it, including placing a / on the end of target. still creates the html folder, 
```
    # Copying files and artifacts via SSH
    - name: Copying files to server www
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: false
        source: "./html/*,!.git*,!README.md"
        target: "${{ vars.REMOTE_TARGET }}"
```
Any solution or flag to change this behaviour?
