### ISSUE TITLE
Probleme password ou ssk-key

### ISSUE THREAD

**Issue by Grezor** [appleboy/scp-action#135]
hello, I am creating an issue for help.

Having already performed in 2019. I can't remember how this works.

I have an error, I would like to know if ssk-key is generated on the pc, or on the server?

Thanks for your help :)

```
name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }} <--- here
      with:
        source: "."
        target: "/var/www/duplessigeoffrey.fr"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }} <--- here
```

![imagekey](https://github.com/appleboy/scp-action/assets/38507456/b7533066-a482-4483-8aae-b13867d259c3)
