### ISSUE TITLE
drone-scp error:  Process exited with status 1

### ISSUE THREAD

**Issue by reza00farjam** [appleboy/scp-action#144]
Hi,
I have this simple setup:

```yaml
- name: Upload build files to VPS via SSH
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.SSH_HOST }}
    port: ${{ secrets.SSH_PORT }}
    username: ${{ secrets.SSH_USERNAME }}
    password: ${{ secrets.SSH_PASSWORD }}
    rm: true
    source: build/web/*
    target: ${{ secrets.SCP_TARGET }}
```

But it ends up with this error:

```
tar all files into /tmp/RmOmwBuqmG.tar.gz
scp file to server.
Remove target folder: ***
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file RmOmwBuqmG.tar.gz
2023/09/[27](https://github.com/CSE-Archive/archive-ui/actions/runs/6319969406/job/17161778620#step:9:28) 00:54:42 Process exited with status 1  
```

My `SCP_TARGET` is `/var/www/csearchive.com/html`.
