### ISSUE TITLE
ssh: command failed

### ISSUE THREAD

**Issue by CheeseTastisch** [appleboy/scp-action#145]
Every time I try to copy my files I get the following error:
`2023/10/05 11:15:16 error copy file to dest: ***, error message: ssh: command scp -tr SagKakNsXw.tar.gz failed`

This is my action:
```yml
- name: Copy Files
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    port: ${{ secrets.PORT }}
    source: "build/libs/core.jar,build/libs/library.jar"
    target: "/plugins"
```
