### ISSUE TITLE
drone-scp error:  error copy file to dest: ***, error message: Process exited with status 5

### ISSUE THREAD

**Issue by birch-ui** [appleboy/scp-action#146]
Hi,
I have configured it as shown in the code below.

```yaml
- name: Upload Changed files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_KEY }}
          passphrase: ${{ secrets.SFTP_PASSPHRASE }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: “/home/www/test/"
          overwrite: true
```

However, an error like the one below was displayed.

```bash
tar all files into /tmp/aALrqfzooP.tar.gz
scp file to server.
2023/10/17 01:12:58 error copy file to dest: ***, error message: Process exited with status 5
drone-scp error:  error copy file to dest: ***, error message: Process exited with status 5
```

We have not encountered a case of a status 5 error, and thus, we have been unable to resolve it.
I would appreciate your assistance.
