### ISSUE TITLE
Can't unlink already-existing object, Process exited with status 1

### ISSUE THREAD

**Issue by Michale-Nguyen** [appleboy/scp-action#148]
job:
```
- name: deploy srouce code
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.STAGING_SERVER_HOST }}
        username: ${{ secrets.STAGING_SERVER_USERNAME }}
        password: ${{ secrets.STAGING_SERVER_PASSORD }}
        port: ${{ secrets.STAGING_SERVER_PORT }}
        source: "${{ secrets.STAGING_SERVER_FOLDER_WEBAPI }}/*.*"
        target: ${{ secrets.STAGING_SERVER_FOLDER }}
``` 
error:
```
***/Serilog.dll: Can't unlink already-existing object
***/Service.dll: Can't unlink already-existing object
***/Swashbuckle.AspNetCore.Annotations.dll: Can't unlink already-existing object
***/Swashbuckle.AspNetCore.Swagger.dll: Can't unlink already-existing object
***/Swashbuckle.AspNetCore.SwaggerGen.dll: Can't unlink already-existing object
***/Swashbuckle.AspNetCore.SwaggerUI.dll: Can't unlink already-existing object
***/System.Configuration.ConfigurationManager.dll: Can't unlink already-existing object
***/System.IdentityModel.Tokens.Jwt.dll: Can't unlink already-existing object
***/Utilities.dll: Can't unlink already-existing object
***/runtimes/win-x64/native/sni.dll: Can't unlink already-existing object
***/runtimes/win/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll: Can't unlink already-existing object
***/runtimes/win/lib/netcoreapp2.1/System.Data.SqlClient.dll: Can't unlink already-existing object
tar: Error exit delayed from previous errors.

drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
``` 
i try stop site in iis then try this job => don't success
if i stop site longer and try this job success
how to replace file running like that, 
Thanks you
