### ISSUE TITLE
Action works fine, but still getting a "connection refused"

### ISSUE THREAD

**Issue by C0ntroller** [appleboy/scp-action#152]
Hi,

I just tried to use your action but ran into a weird issue.

The log says:
```
tar all files into /tmp/cviVHRTWNY.tar.gz
scp file to server.
create folder /var/www/website/astro
untar file cviVHRTWNY.tar.gz
remove file cviVHRTWNY.tar.gz
drone-scp error:  dial tcp <ip-address>:22: connect: connection refused
drone-scp rollback: remove all target tmp file
remove file cviVHRTWNY.tar.gz
2023/12/14 15:12:54 dial tcp <ip-address>:22: connect: connection refused
```
So it seems like deleting the temporary file failed 2 times - initially and when you try to rollback.

My config is the following:
```
    - name: Copy files via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: c0ntroller.de
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: "/var/www/website/astro"
        overwrite: true
        strip_components: 1
```

All the files were copied, and even the temporary file was deleted.
The SSH-log also shows no connection refused either.
So it seems like everything actually works perfectly, but the action just logs an error and the pipeline won't finish correctly.

Any help?
