### ISSUE TITLE
tar: can't open '/home/runner/work/_temp/kCTvmuuHYr.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by thermoweb** [appleboy/scp-action#168]
Hi,

I have the following configuration: 
```yaml
- name: publish site
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_KEY }}
    passphrase: ${{ secrets.SSH_PASSPHRASE }}
    source: "public/"
    target: "/var/www/mysite"
    overwrite: true
```

I tried a lot of things to make it works but I'm stuck with this error:
```bash
tar: can't open '/home/runner/work/_temp/kCTvmuuHYr.tar.gz': No such file or directory
exit status 1
drone-scp version: v1.6.14
tar all files into /home/runner/work/_temp/kCTvmuuHYr.tar.gz
```

I checked with ssh-action which works great so it might be an issue with the scp tar stuff.

Thanks in advance for your help.
