### ISSUE TITLE
Unable to copy content of the artifact into target

### ISSUE THREAD

**Issue by gurpreet-fe** [appleboy/scp-action#191]
**Description**
I would like to copy only the contents of the artifact into the target directory.

**Expected Behaviour**
The contents of the artifact should be copied directly into the target directory, without copying the artifact directory itself.

```yaml
- name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: dist/*
          target: ~/public_html/remote/
          rm: true
```

**Actual Behaviour**
The entire artifact directory is copied to the target directory.

![Screenshot 2024-11-16 at 18 14 47](https://github.com/user-attachments/assets/f791c2c4-9701-4ae5-a935-7b36bf6031ba)

**Comment by eliezerfot123** [comment]
Hello, I also have the same problem apparently is not taking the * or in case such paths example dist/folder/folder2/* in the final destination is coming the same structure remote/dist/folder/folder2/ when I really want to show in remote/ what is inside the folder2 would be great if you can fix this bug. Thanks

**Comment by yarobash** [comment]
Have the save issue.

**Comment by brleonardo** [comment]
To solve this I had to use [appleboy/ssh-action](https://github.com/appleboy/ssh-action).

- Put this step after the SCP step; This will move the files from dist to parent directory.

```
- name: Move files to root
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd *PATH TO PARENT DIRECTORY*
            mv dist/* .
            rm -rf dist/
```

**Comment by arthurxxy** [comment]
Have the save issue.

**Comment by eliezerfot123** [comment]
@brleonardo thank you! 

I will try and leave a comment here

**Comment by ttodua** [comment]
there should be an additional option for that, would be good if implemented

**Comment by appleboy** [comment]
Add the following config:


```yaml
      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: dist/*
          target: ~/public_html/remote/
          rm: true
          strip_components: 1
```

![image](https://github.com/user-attachments/assets/c68c5be5-645e-4736-8263-3bb15ac16f6d)
