### ISSUE TITLE
Permission inheritance

### ISSUE THREAD

**Issue by ttodua** [appleboy/scp-action#192]
this action seems to have some permission & inheritance issues.
for example, setup a directory on a remote machine with this:
```
sudo addgroup group1
adduser githubuser
usermod -aG group1 githubuser
usermod -aG group1 www-data
sudo chown -R :group1 /var/www/
sudo chmod -R 2770 /var/www/
# inherit permissions on created folders & files within dir
setfacl -R -d -m g::rwx /var/www/
```

then, when using:
```
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PASSWORD }}
          source: "!.git,*"
          target: /var/www/
          strip_components: 0
          overwrite: true
```

after action copies folders through ssh there (into `/var/www` dir) the folders there are having `2750` instead of `2770`, causing `www-data` users being unable to access those file/folders.

so, it's crucial that group permissions were correctly inherited. 
any thoughts? thanks
