### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Madoshakalaka** [appleboy/scp-action#194]
This was running fine for us:

```yml
- uses: actions/download-artifact@v4
  with:
    name: new-build
# this downloads an execubible file `backend` to the current directory 

- name: Upload Artefact
  uses: nicklasfrahm/scp-action@main
  with:
    direction: upload
    fingerprint: ${{ env.FINGERPRINT }}
    host: ${{ env.HOST }}
    username: our_user
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    source: backend
    target: /opt/our_app/backend
```

but we recently have to download the artifact to a different place because of a name clash with a directory, the new steps:

```yml
- uses: actions/download-artifact@v4
with:
  name: new-build
  path: /tmp

- run: ls /tmp
# this shows clearly the file is downloaded to `/tmp/backend`

- name: Upload Artefact
uses: nicklasfrahm/scp-action@main
with:
  direction: upload
  fingerprint: ${{ env.FINGERPRINT }}
  host: ${{ env.HOST }}
  username: our_user
  key: ${{ secrets.SSH_PRIVATE_KEY }}
  source: /tmp/backend
  target: /opt/our_app/backend
```

And now somehow scp-action fails with "No such file /tmp/backend"??
