### ISSUE TITLE
Issue with `rm: true` Option Causing SSH Authentication Failure

### ISSUE THREAD

**Issue by jhon3242** [appleboy/scp-action#195]
Hello there ✋ 
I encountered an SSH authentication failure when using the `rm: true` option in scp-action. My setup is as follows.
```yaml
- uses: actions/checkout@v4
- name: copy file via ssh password
  uses: appleboy/scp-action@master
  with:
    host: ${{ env.HOST }}
    username: ${{ secrets.STAG_USERNAME }}
    key: ${{ secrets.STAG_SSH_KEY }}
    port: 22

    proxy_host: ${{ secrets.STAG_BASTION_IP }} # Bastion server IP
    proxy_username: ${{ secrets.STAG_USERNAME }} # Bastion server SSH user
    proxy_key: ${{ secrets.STAG_SSH_KEY }} # Bastion server SSH Private Key
    proxy_port: 22

    source: "./deployment/staging/deploy.sh"
    target: /home/atcha/
    rm: true
```
When running the workflow with rm: true, I get the following error.
> ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey]

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/44db5fc2-1277-462e-a767-bd3b9183046d" />

Here are some details about my environment:
- OS: Ubuntu 24.04 LTS
- SSH Key: Generated using ed25519 algorithm following the [official guide](https://github.com/appleboy/scp-action#if-you-are-using-openssh).

Additionally, once this error occurs, even after removing `rm: true` and retrying, the workflow no longer works as expected. Previously successful runs fail to authenticate, suggesting a persistent issue triggered by the `rm: true` option.

Has anyone else encountered this issue? Any insights would be greatly appreciated!

ps. Interestingly, the **issue can be resolved by generating a new SSH key** and updating the secrets with the new key. However, this is not an ideal solution, as it suggests that something is causing the existing key to become invalid after the initial failure.
