### ISSUE TITLE
a dedicated setting for excluding folder

### ISSUE THREAD

**Issue by kirmola** [appleboy/scp-action#205]
is it possible to exclude certain folders from being copied, if no, please add that

**Comment by Obcodelab** [comment]
@kirmola has this been added?
Also looking for a way to exclude some files and folders

**Comment by kirmola** [comment]
Yeah

**Comment by ondanieldev** [comment]
on `source` property, you can send a list of folders by separating them with commas. You can add a `!` prefix to the ones you want to skip.

on the example below I copy everything from my `.` (root) folder  except by my `node_modules` folder:


```
- name: Copy to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secretsSERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: '.,!node_modules'
          target: '~/app'
          overwrite: true
          rm: true
          timeout: 300s
```

**Comment by ondanieldev** [comment]
> is it possible to exclude certain folders from being copied, if no, please add that

on `source` property, you can send a list of folders by separating them with commas. You can add a `!` prefix to the ones you want to skip.

on the example below I copy everything from my `.` (root) folder  except by my `node_modules` folder:


```
- name: Copy to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secretsSERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: '.,!node_modules'
          target: '~/app'
          overwrite: true
          rm: true
          timeout: 300s
```
