### ISSUE TITLE
Step "Run actions/checkout@master" started to fail

### ISSUE THREAD

**Issue by erikw** [appleboy/scp-action#24]
Hello!

I've used this action successfully for a while. Last time I used it was 2020-04-13. Today I pushed another commit to the master branch but discovered that this action now failed. No changes has been made to the repository or the Github settings for it in this time period.

It fails on the step "Run actions/checkout@master":

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +7eb330784af3dfa9a43fe441df0a2d9c023***452:refs/remotes/origin/master
  remote: Repository not found.
  ##[error]fatal: repository 'https://github.com/***/***.me/' not found
  The process '/usr/bin/git' failed with exit code 128
```
![Screen Shot 2020-05-22 at 19 44 54](https://user-images.githubusercontent.com/175286/82695103-becd2700-9c64-11ea-8391-291d7799ba19.png)

When I look at this part of the step from 13th of April, it looks like:

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +b89cd8a4f3f670120874fa7d4ea5854c154b791b:refs/remotes/origin/master
  remote: Enumerating objects: 26, done.        
  remote: Counting objects:   3% (1/26)
[...]        
...
```
![Screen Shot 2020-05-22 at 19 44 35](https://user-images.githubusercontent.com/175286/82695142-d60c1480-9c64-11ea-9a63-0e1f1d5c9bcf.png)

Any ideas what can have happended here for this Action to break?
If there's any way I can provide more information I'd be happy to!

My Actions config looks like:

```yaml
name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.deploy_HOST }}
        port: ${{ secrets.deploy_PORT }}
        username: ${{ secrets.deploy_USERNAME }}
        key: ${{ secrets.deploy_KEY }}
        passphrase: ${{ secrets.deploy_PASSPHRASE }}
        rm: true
        source: "*,.*,!.git,!.github"
        target: "/var/www/"
```
