### ISSUE TITLE
dial tcp: lookup on ***: no such host

### ISSUE THREAD

**Issue by raoulvdberge** [appleboy/scp-action#26]
Hi there,

scp-action keeps failing randomly. It is able to upload the files, create folders, etc. But when it's finished, it throws this error and removes all uploaded files again.

Any idea why?

https://github.com/refinedmods/website/runs/768264891?check_suite_focus=true

**Comment by appleboy** [comment]
post your YAML config?

**Comment by raoulvdberge** [comment]
```yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build-website
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: output
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/minecraft/refinedmods/public"
        rm: true
        strip_components: 1
```
