### ISSUE TITLE
Have to set environment variables not like README

### ISSUE THREAD

**Issue by k----n** [appleboy/scp-action#27]
It appears that the following works:
```
    - name: copy files
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
      with:
        source: "*"
        target: "test"
        rm: true
```

But this does not work (config similar to README):
```
    - name: copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "*"
        target: "test"
        rm: true
```
