### ISSUE TITLE
dial tcp ***:***: connect: connection timed out

### ISSUE THREAD

**Issue by haron4igg** [appleboy/scp-action#29]
Hi! 

My pipeline worked fine before, but after some time of inactivity, i keep getting this error periodically. I have few steps with this plugin, one step runs fine, but second step - i get this error. Next run - opposite, first step fails.

```
deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
- name: Upload Artifacts to Host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCP_DEP_HOST }}
        port: ${{ secrets.SCP_DEP_PORT }}
        username: ${{ secrets.SCP_DEP_LOGIN }}
        password: ${{ secrets.SCP_DEP_PASSWORD }}
        timeout: 5m
        command_timeout: 20m
        target: /
        source: ./package.zip
        rm: true
     
- name: Deploy Artifacts
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SCP_DEP_HOST }}
    username: ${{ secrets.SCP_DEP_LOGIN }}
    password: ${{ secrets.SCP_DEP_PASSWORD }}
    port: ${{ secrets.SCP_DEP_PORT }}
    script: |
```
Log: 
```
 Upload Artifacts to Host2m 11s
    proxy_use_insecure_cipher: false
    port: ***
    username: ***
    password: ***
    timeout: 5m
    command_timeout: 20m
    target: /
    source: ./package.zip
    rm: true
    use_insecure_cipher: false
    debug: false
    strip_components: 0
    overwrite: false
    proxy_port: 22
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
/usr/bin/docker run --name d3bffe8c1d0bd641cfb39dfaab147212d4_577fdd --label 3888d3 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_PORT -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_TARGET -e INPUT_SOURCE -e INPUT_RM -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_PASSPHRASE -e INPUT_FINGERPRINT -e INPUT_USE_INSECURE_CIPHER -e INPUT_DEBUG -e INPUT_STRIP_COMPONENTS -e INPUT_OVERWRITE -e INPUT_TAR_TMP_PATH -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_USE_INSECURE_CIPHER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/repo/repo":"/github/workspace" 3888d3:bffe8c1d0bd641cfb39dfaab147212d4
tar all files into /tmp/053165802/SNY0dNo24S.tar
scp file to server.
2020/06/24 20:17:08 error copy file to dest: ***, error message: dial tcp ***:***: connect: connection timed out
drone-scp error:  error copy file to dest: ***, error message: dial tcp ***:***: connect: connection timed out

```
