### ISSUE TITLE
ssh: command mkdir -p test failed

### ISSUE THREAD

**Issue by enginaar** [appleboy/scp-action#3]
Hello,

I'm afraid I'm failing to use this action properly. I'm trying to upload files to the root folder of my ssh user account but wasn't able to get past the error below when executing scp-action step in my workflow. I've finally tried with a target folder name but still getting the same error.   

> 14 tar all files into /tmp/236545441/HvzhGMeDQa.tar
15 scp file to server.
16 create folder test
17 drone-scp error:  ssh: command mkdir -p test failed
18 drone-scp rollback: remove all target tmp file
19 remove file HvzhGMeDQa.tar
20 2019/10/08 00:46:29 ssh: command mkdir -p test failed
21 ##[error]Docker run failed with exit code 1

my yaml file is like below

```yaml
- name: Deploy to staging
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.STAGING_HOST }}
    username: ${{ secrets.STAGING_USER }}
    password: ${{ secrets.STAGING_PASS }}
    source: "*"
    target: "test"
```

- Tried both with an existing and non-existing folder. Both failed with same error.
- I can see the HvzhGMeDQa.tar and other tar files from previous attempts in the root folder. 
- I can create folders with the same username and password via SFTP.

Thank you

**Comment by devmount** [comment]
Same here. This config:

```yml
- name: Push add-on to CDN
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.CDN_HOST }}
    username: ${{ secrets.CDN_USER }}
    password: ${{ secrets.CDN_PASS }}
    port: ${{ secrets.CDN_PORT }}
    source: "artifact.xpi"
    target: "${{ secrets.CDN_PATH }}"
```

throws these errors:

```log
tar all files into /tmp/625984187/DazHGN4sSL.tar
scp file to server.
create folder ***/
drone-scp error:  ssh: command mkdir -p ***/ failed
drone-scp rollback: remove all target tmp file
remove file DazHGN4sSL.tar
2021/01/29 10:54:11 ssh: command mkdir -p ***/ failed
```

Any update on this?
