### ISSUE TITLE
Error: Empty tar archive with artifact download

### ISSUE THREAD

**Issue by chgad** [appleboy/scp-action#35]
Hello everyone,
i'm experience the following error

    tar all files into /tmp/934282472/j1Gg65oXbW.tar
    tar: empty archive
    exit status 1

when trying to upload the files/directories of an artifact to a server with the following workflow:

    deploy-dive-staging-gh:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - run: mkdir ~/distfiles
        - uses: actions/download-artifact@v2
          with:
            name: distfiles
            path: ~/distfiles

        - name: Deploy dive preview
          uses: appleboy/scp-action@v0.0.10
          with:
            host: ${{ secrets.SERVER }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            rm: true
            source: "/home/runner/distfiles"
            target: "${{ secrets.TARGET_DIR }}"

I have verified that the source-directory is not empty and all files are there (verfiead vai adding `- run: ls -R ~/distfiles`.

So why do i get this error?

**Comment by ShepardEG** [comment]
Same issue

**Comment by GRcwolf** [comment]
I had the same issue however i could fix it by removing the '~' and just use the relative paths.
So in your case I did something like this:
```yml
deploy-dive-staging-gh:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v2
    - run: mkdir ~/distfiles
    - uses: actions/download-artifact@v2
      with:
        name: distfiles
        path: distfiles

    - name: Deploy dive preview
      uses: appleboy/scp-action@v0.0.10
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: true
        source: distfiles/*
        target: "${{ secrets.TARGET_DIR }}"
```
Note that I have changed both the path where the artifact is saved and the source of the scp action.
I hop this can also solve your problem.
