### ISSUE TITLE
Is it possible to add `env` support? My `target` is stored as an `env`

### ISSUE THREAD

**Issue by williamli** [appleboy/scp-action#38]
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: /var/www/bcapp-wp/wp/wp-content/plugins/custom-admin-plugin
...
   - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          rm: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "."
          target: $DEPLOY_PATH
...
```

Right now the above fails and there is no way for me to pass `envs` to the action as https://github.com/marketplace/actions/ssh-remote-commands.

What is the best way to pass DEPLOY_PATH to the action?
