### ISSUE TITLE
SCP to Windows Server Successful Transfer, Fails to send to send to the correct folder.

### ISSUE THREAD

**Issue by ThomasAunvik** [appleboy/scp-action#39]
```
tar all files into /tmp/015153750/RT1CGuDSlw.tar
scp file to server.
create folder ***
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file RT1CGuDSlw.tar
2020/09/16 14:40:30 Process exited with status 1
```
SCP Action fails, but SSH Action works (when it is above SCP Action), which implies that there is nothing wrong with the ssh connection.

STAGING_TARGET_UPLOAD tested with these inputs:
* `C:\Users\username\targetFolder`
* `C:\Users\username\targetFolder\`
* `targetFolder`

```yml
    - name: Upload to Staging
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.STAGING_SSH_HOST }}
        port: ${{ secrets.STAGING_SSH_PORT }}
        username: ${{ secrets.STAGING_SSH_USERNAME }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
        source: ProductionInsight/Web/bin/Release/netcoreapp3.1/publish/
        target: ${{ secrets.STAGING_TARGET_UPLOAD }}

    - name: Execute Extraction Command
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          script: ${{ secrets.STAGING_EXTRACT_SCRIPT }}
```

Is there a way to debug this error, cause there is not much useful information given.
