### ISSUE TITLE
Ignore files with extension

### ISSUE THREAD

**Issue by paolorr** [appleboy/scp-action#42]
I'm trying to skip all the files with `.spec.js` extension in any folder, but it's not working, these files are also copied
```yml
      - name: Copy files to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "package.json,yarn.lock,dist,tmp,uploads,!**/*.spec.js"
          target: "~/app"
```
What am I missing?
