### ISSUE TITLE
How to scp a directory recursively?

### ISSUE THREAD

**Issue by CPPAlien** [appleboy/scp-action#47]

**Comment by pascalandy** [comment]
I trying to hack my way this as well. Syntax is not clear so far.

**Comment by pascalandy** [comment]
Here is how I was able to do it:

## the build

`${{ env.HOMMY }}` is at the root of the github actions workspace.
The final build is `${{ env.THEME_NAME }}`

```
      -
        name: Build theme | ${{ env.THEME_NAME }}
        # It looks funny that we zip the theme to unzip it. The reason is that ghost developper optimize themes and zippin it is only one part of the equation.
        # When building the zip file goes to /dist
        run: |
          cd ${{ env.HOMMY }} && mkdir -pv tmp && cd ${{ env.HOMMY }}/tmp
          git clone --depth=1 https://github.com/${{ env.REPO_TO_CLONE }}
          mv Dope ${{ env.THEME_NAME }}
          cd ${{ env.HOMMY }}/tmp/${{ env.THEME_NAME }}
          yarn && yarn zip
          unzip -o ${{ env.HOMMY }}/tmp/${{ env.THEME_NAME }}/dist/${{ env.THEME_NAME }}.zip -d ${{ env.HOMMY }}/${{ env.THEME_NAME }}
          rm -rf ${{ env.HOMMY }}/tmp
          cd ${{ env.HOMMY }}/${{ env.THEME_NAME }}
          ls -AlhF
          pwd 
          cd ${{ env.HOMMY }}
```

## sync the build

```
      -
        name: Upload theme to play-with-ghost.com | via SSH
        if: ${{ success() }}
        #if: github.ref == 'refs/heads/master'
        uses: appleboy/scp-action@v0.1.1
        with:
          host: "${{ secrets.NODE1 }},${{ secrets.NODE2 }},${{ secrets.NODE3 }}"
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_ACTIONS }}
          passphrase: ${{ secrets.SSH_KEY_ACTIONS_PASSPHRASE }}
          # The action directory use the workspace as default. We cannot do /zxc/zxc/${{ env.THEME_NAME }}/* at the source
          source: "${{ env.THEME_NAME }}/*"
          target: "${{ secrets.SSH_PWG_THEME_PATH_DOPE }}/content/themes"
```

**Comment by appleboy** [comment]
directory structure:

```
foo/
bar/
```

Just following YAML config to SCP `bar` folder:


```yaml
      -
        name: Upload theme to play-with-ghost.com | via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: "${{ secrets.NODE1 }},${{ secrets.NODE2 }},${{ secrets.NODE3 }}"
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_ACTIONS }}
          passphrase: ${{ secrets.SSH_KEY_ACTIONS_PASSPHRASE }}
          source: "bar/*"
          target: "content/themes"
```
