### ISSUE TITLE
source path is not working as expected

### ISSUE THREAD

**Issue by koolwithk** [appleboy/scp-action#50]
Below code copying the code inside  `/home/user1/web/user1/public_html/dist/note/` ?

```
        name: deploy with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist/note/*"
          target: "/home/user1/web/user1/public_html"
          overwrite: true
          rm: true
```

But it  should copy the code from `./dist/note/*`  to `/home/user1/web/user1/public_html`
