### ISSUE TITLE
Error: Input required and not supplied: key

### ISSUE THREAD

**Issue by Gutyerrez** [appleboy/scp-action#53]
I receive this error:

```
Run shimataro/ssh-key-action@v2
  with:
    name: id_rsa
    if_key_exists: fail
  env:
    GOROOT: /opt/hostedtoolcache/go/1.16.3/x64
Error: Input required and not supplied: key
```

My action:

```
on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: deub
        run: echo $KNOWN_HOSTS
        env:
          KEY: ${{ secrets.DEDICATED_1_SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEDICATED_1_SSH_KEY }}
      - name: Deploy to all servers
        run: scp ${{ github.workspace }}/src/nyrah ${{ secrets.DEDICATED_1_USER }}@${{ secrets.DEDICATED_1_HOST }}:/root
```

My secrets

![image](https://user-images.githubusercontent.com/36475012/116779271-bb811480-aa4b-11eb-9626-3b706f948a1e.png)
