### ISSUE TITLE
How can we copy file from server to local?

### ISSUE THREAD

**Issue by ayushmishra2005** [appleboy/scp-action#54]
I am able to push a file from local to server using below script.

```
 - name: Copy File Via Ssh Password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "*.tar.xz"
          target: "~"
```

How can I do vice versa? How can I pull file from server?
