### ISSUE TITLE
if else statement example?

### ISSUE THREAD

**Issue by zigang93** [appleboy/scp-action#55]
```yml
- name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ env.HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: ${{ secrets.HOST_PORT }}
          KEY: ${{ secrets.CICD_SSH_KEY }} # private ssh
        with:
          source: "./dist"
          target: "/var/www/html/wms/" # <--- if else statement on github branch push
          strip_components: 3 
          rm: true
```
