### ISSUE TITLE
scp-action doesn't respect default working-directory

### ISSUE THREAD

**Issue by andy-blum** [appleboy/scp-action#56]
Config:
```yml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scraper
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.14.0'
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: npm ci
    - name: Build Artifacts
      run: npm run start
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "scraper/dist"
        target: "path/to/target"
        use_insecure_cipher: true
```

To be clear, the above config is _working_, but I have to enter `scraper` in as the source when I would expect the command to be executed from within that directory because of `jobs.<job-id>.defaults.run.working-directory`
