### ISSUE TITLE
drone-scp error:  tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by holmofy** [appleboy/scp-action#57]
mysql scp action config like this: 
```yaml
    - name: SCP Files
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{secrets.PASSPHRASE}}
        source: "starter/target/starter-${{github.event.inputs.revision}}.jar"
        target: "~/apollo-starter-${{github.event.inputs.revision}}.jar"
```
The file has been copied successfully, I can see this file on the server. 
But an error still occurred, causing the subsequent action to fail to execute.
```sh
tar all files into /tmp/380452031/xOTinPD8mN.tar
scp file to server.
create folder ~/apollo-starter-1.0-SNAPSHOT.jar
drone-scp error:  tput: No value for $TERM and no -T specified
```

**Comment by appleboy** [comment]
try the following setting

```yaml
    - name: SCP Files
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{secrets.PASSPHRASE}}
        source: "starter/target/starter-${{github.event.inputs.revision}}.jar"
        target: "~/"
        strip_components: 2
```
