### ISSUE TITLE
Error: can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by Giuliopime** [appleboy/scp-action#58]
My ci.yaml file

```yaml
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
        with:
          source: "."
          target: "/var/www/html/gportal"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: npm i && npm run generate
```

I've set my KEY secret in the repo to
```
-----BEGIN RSA PRIVATE KEY-----
M**keyhere**w=
-----END RSA PRIVATE KEY-----
```

And I get
```
Copy repository content via scp
2021/07/25 13:11:52 Error: can't connect without a private SSH key or password
```

Can't really understand where my issue is.

**Comment by nweiler** [comment]
I'm having a very similar issue.

    - name: Copy file via ssh
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
      with:
        source: "target/*.jar"
        target: "test"

With these env vars:
![Screen Shot 2022-02-22 at 10 48 42 AM](https://user-images.githubusercontent.com/424127/155168232-99e3dadb-a6c2-41c1-b1f9-ee1a13edbda5.png)

Yields this error:
`2022/02/22 15:45:23 Error: can't connect without a private SSH key or password`

Based on the docs it appears I'm using it correctly. Not sure why the action isn't recognizing the private key.

**Comment by aidoit** [comment]
I have the same issue , how to fix it? Is it related to server configuration?

**Comment by changty** [comment]
I had to define the name of the environment that has all the properties to make this work
```
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: main < -- here 
    steps:
    - uses: actions/checkout@v2
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
```

**Comment by firassziedan** [comment]
@changty Thanks 
Add the `environment` key fix this issue

**Comment by aarondavidgepersonal** [comment]
![image](https://user-images.githubusercontent.com/114311538/193057364-e33ba89e-2e08-478b-9f02-2984363ed8f2.png)

![image](https://user-images.githubusercontent.com/114311538/193057599-92595880-c72f-401a-bd61-cf0ae25f7a92.png)

![image](https://user-images.githubusercontent.com/114311538/193057801-1979b4db-d2fa-4b3f-813b-5735c2f5a93a.png)


Keep getting the same issue. 
Can't for the life of me figure out why it's not recognizing my key.

**Comment by aarondavidgepersonal** [comment]
![image](https://user-images.githubusercontent.com/114311538/193073402-8f6bb1ed-daab-4077-be5d-96354d68f448.png)

**Comment by aarondavidgepersonal** [comment]
https://stackoverflow.com/q/73897889/20106335

**Comment by TadeoArmenta** [comment]
In my case, was just a matter of making all the connection-related keys to caps

```
env:
    HOST: ${{ secrets.HOST }}
    KEY: ${{ secrets.KEY }}  # I had this one lowercase
    USERNAME: ${{ secrets.USERNAME }}
    PORT: ${{ secrets.PORT }}
```
