### ISSUE TITLE
Can't copy content inside directory

### ISSUE THREAD

**Issue by jd-0001** [appleboy/scp-action#59]
Hi,

Thanks for this great action. I tried `scp-action` and it is working really well except, I want to upload whole content inside the directory and if I try it using below yml it isn't working:

```yml
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download artifacts from build
      uses: actions/download-artifact@v2
      with:
        name: distdir
        path: documentation
        
    - name: List current dir after download
      shell: bash
      run: ls
      
    - name: List documentation content after download
      shell: bash
      run: ls documentation

    - name: Upload dist content via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: documentation/*
        target: ${{ secrets.TARGETDIR }}
        rm: true
```

- `List current dir after download` outputs:
```
documentation
src
package.json
... other files
```

- `List documentation content after download` outputs:
```
index.html
favicon.icon
... other files
```

My target dir is `/var/www/{somePath}/demo/{themeName}/documentation` and I want to paste all content of documentation dir to the `/var/www/{somePath}/demo/{themeName}/documentation` but using `source: documentation/*` isn't working.

Also, I am using `rm: true` because I want to remove the existing target dir `/var/www/{somePath}/demo/{themeName}/documentation` before uploading.

Regards.

**Comment by Varin6** [comment]
Same issue here, my yml:

`name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CoffeeTime.sln
    - name: Build
      run: dotnet build CoffeeTime.sln --no-restore
    - name: Test
      run: dotnet test CoffeeTime.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./CoffeeTime.Api/CoffeeTime.Api.csproj -o coffee
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "coffee/*"
        target: "/var/www/test"
        `
Tried `coffee/*`, `coffee/*.*`, `coffee/**` - nothing works, it always copies the whole `coffee` directory rather than just all the files inside.

**Comment by Varin6** [comment]
@jd-0001 Ok, just found a solution to this. It is:

`strip_components: 1`

Parameter. 

Last bit of your code should be:

```
 - name: Upload dist content via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "documentation/"
        target: ${{ secrets.TARGETDIR }}
        strip_components: 1
```

Notice slash at the end of `source` path and no `*` 
I have not tested this with `rm: true` flag, so not sure how this would work.

**Comment by jd-0001** [comment]
Will let you know once I implement this in my new repo 👍🏻

**Comment by Xwilarg** [comment]
I tried the code of Varin6 but it still doesn't work for me:
```
uses: appleboy/scp-action@master
env:
    HOST: ${{ secrets.DEPLOY_HOST }}
    USERNAME: ${{ secrets.DEPLOY_USER }}
    PORT: 22
    KEY: ${{ secrets.DEPLOY_SSH_KEY }}
with:
    source: "./build/"
    target: ${{ env.DEPLOY_TARGET }}
    strip_components: 1
```

**Comment by indymaat** [comment]
The parameter **strip_components** with value **1** did work for me:
```
- name: Copy Build Via SSH
  uses: appleboy/scp-action@master
  with:
    source: dist/
    strip_components: 1
    target: ~/project
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_KEY }}
    passphrase: ${{ secrets.SSH_PASSPHRASE }}
```
