### ISSUE TITLE
source to target file copying, kinda confusing

### ISSUE THREAD

**Issue by seanmavley** [appleboy/scp-action#6]
``` 
   - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: domain.com
        USERNAME: user
        PORT: 22
        KEY: ${{ secrets.forSSH }}
      with:
        source: "./dist/pwa/"
        target: "/home/user/domain.com/pwa/"
```

So I build angular with `ng build --prod`. The files end up in the `./dist/pwa` folder

I want to copy contents (only the contents of) the `./dist/pwa` folder, into the server, at `/home/user/domain.com/pwa`

To put in perspective, here's how I do with a normal scp command
`scp -r ./dist/pwa/* domain@domain.com://home/user/domain.com/pwa`

What am I missing? With the above github action, it copies the file to here:

`/home/user/domain.com/pwa/dist/pwa` instead of `/home/user/domain.com/pwa`
