### ISSUE TITLE
Error copy file to dest: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by aaron5670** [appleboy/scp-action#67]
After the new update (v0.1.2) I can't deploy with this action.

See logs:
```
tar all files into /tmp/894175415/MCfQNsJWzG.tar
scp file to server.
2021/10/25 11:38:02 error copy file to dest: demo.website.com, error message: wait: remote command exited without exit status or exit signal
drone-scp error:  error copy file to dest: demo.website.com, error message: wait: remote command exited without exit status or exit signal
```

**Comment by fachreza73** [comment]
@aaron5670 can you share your yml file?

**Comment by aaron5670** [comment]
@fachreza73 ofcourse! 😃 

```yaml
name: Build Wordpress Theme and Deploy

on:
  push:
    paths:
      - 'wp-content/themes/theme/**'

    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install NPM modules
      - run: cd wp-content/themes/theme && npm ci

      # Build wordpress theme
      - run: cd wp-content/themes/theme && npm run build --if-present

      # Create wordpress theme
      - run: cd wp-content/themes/theme && npm run archive --if-present

      # Deploy to host
      - name: copy file via SSH key
        uses: appleboy/scp-action@master
        with:
          host: demo.myprivatewebsite.nl
          username: username
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          source: "wp-content/themes/theme/package/theme/*"
          target: "public_html/wp-content/themes/theme"
          strip_components: 5
          rm: true
```
