### ISSUE TITLE
tar: empty archive - Docker run failed with exit code 1 

### ISSUE THREAD

**Issue by alan345** [appleboy/scp-action#7]
I could not understand which variable could be wrong?
We maybe need a better error message?

```
  with:
    host: ***
    username: ***
    key: ***
    port: 22
    source: ~/exportServer/backup.sql
    target: ~/backup.sql
    timeout: 30s
    command_timeout: 10m
    strip_components: 0
    overwrite: false
/usr/bin/docker run --name ee6078d19cbf8da4672854dd240c06f80c0_3b33ce --label 671ee6 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_KEY -e INPUT_PORT -e INPUT_SOURCE -e INPUT_TARGET -e INPUT_PASSWORD -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY_PATH -e INPUT_RM -e INPUT_STRIP_COMPONENTS -e INPUT_OVERWRITE -e INPUT_TAR_TMP_PATH -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/nacho/nacho":"/github/workspace" 671ee6:078d19cbf8da4672854dd240c06f80c0
tar: empty archive
tar all files into /tmp/640661935/xqJM6FeoeL.tar
exit status 1
##[error]Docker run failed with exit code 1
```

with colors:
![image](https://user-images.githubusercontent.com/15246526/71701418-20582c00-2d7e-11ea-85dc-d0ba7a21fe33.png)

**Comment by joshp-f** [comment]
I received this issue when the 'source' field pointed to a non-existent folder.
I was able to fix it by using:
`source: "/home/somedir/somedir.../somefile"`

**Comment by appleboy** [comment]
target is the folder path, not the file path.

**Comment by ouoam** [comment]
I have same problem. I use target is the folder path
![image](https://user-images.githubusercontent.com/12713801/79934158-11f06600-847c-11ea-83a8-fdf6d8d0c35b.png)

**Comment by emha** [comment]
I also experience the same error and the target is an existing folder path. The complete GitHub-Repository should be uploaded to the server.

```
- name: DEPLOY to production server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSPHRASE }}
        port: 22
        source: "*"
        target: "/var/www"
```

Any new on this?

**Comment by appleboy** [comment]
I will reproduce the problem first.

**Comment by appleboy** [comment]
@emha What is your error message?

**Comment by emha** [comment]
Same as from @ouoam 

```
Run appleboy/scp-action@master
  with:
    host: ***
    username: ***
    password: ***
    port: 22
    source: *
    target: /var/www
    timeout: 30s
    command_timeout: 10m
    rm: false
    strip_components: 0
    overwrite: false
    proxy_port: 22
    proxy_timeout: 30s
/usr/bin/docker run --name be76db97b4082dab90472a8f86356826aa1eb9_566d0f --label be76db --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_PORT -e INPUT_SOURCE -e INPUT_TARGET -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_PASSPHRASE -e INPUT_RM -e INPUT_STRIP_COMPONENTS -e INPUT_OVERWRITE -e INPUT_TAR_TMP_PATH -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/hy-invest/hy-invest":"/github/workspace" be76db:97b4082dab90472a8f86356826aa1eb9
tar: empty archive
tar all files into /tmp/079140030/854hVs7gnX.tar
exit status 1
```

**Comment by emha** [comment]
In a previous run the last lines were switched. Don't know it this is useful information

```
tar all files into /tmp/208654807/YWZHnv7DXt.tar
tar: empty archive
exit status 1
```

**Comment by appleboy** [comment]
Hi All, the `source` must be an existing file or path. You will get the `tar: empty archive` if `source` does not exist.

**Comment by emha** [comment]
Thanks for investigating!
What would be a correct path for `source` when I want to add all files? `/*` seems not to work as I get the error `removing leading '/' from member names` but a single `*` is working neither as described above.

**Comment by emha** [comment]
I use the same action file in a different repository and the deployment works in there. Now I found that the files weren't exactly the same. The file which throws the error was missing the line
`- uses: actions/checkout@master` before starting with the appleboy script. So the file looks now like this

```
- uses: actions/checkout@master
- name: DEPLOY
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSPHRASE }}
        port: 22
        source: "*"
        target: "/var/www"
```

This seems to be the "bug" which isn't appleboy related because the appleboy script can't access the repository correctly as it isn't allowed to. Do I understand the usage of `actions/checkout@master` correctly?

**Comment by appleboy** [comment]
Please try the latest version

```
- name: SCP Command to Transfer Files
  uses: appleboy/scp-action@v0.0.10
```

**Comment by appleboy** [comment]
See more example:

```
    - name: checkout
      uses: actions/checkout@v1

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.0.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "test"
```
