### ISSUE TITLE
How to override only changed files?

### ISSUE THREAD

**Issue by Arthurolevsky** [appleboy/scp-action#73]
Hi @appleboy,

Could you be so kind as to guide me how to upload to server only changed files?

Thanks in advance.

**Comment by appleboy** [comment]
```yaml
  changes:
    name: test changed-files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true
        separator: ","

    - name: copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        target: test
```
