### ISSUE TITLE
Error: Empty tar archive

### ISSUE THREAD

**Issue by mkhotib20** [appleboy/scp-action#74]
Hello there, i'm facing error when trying to scp my docker compose to server

here is my config
```
 - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          rm: true
          source: 'docker/production/docker-compose.yml'
          target: '~/core-backend/docker-compose.yml'
          strip_components: 2
```

and here is the github action outpu
<img width="760" alt="image" src="https://user-images.githubusercontent.com/23493234/154807305-0c39205f-5360-482b-8d37-595872b45464.png">

thank you 🙏

**Comment by rgstephens** [comment]
I also have this issue. Would prefer an option to disable use of `tar`

**Comment by DesDaugtMa** [comment]
I have the same issue too

**Comment by junxxx** [comment]
I also have the issue

**Comment by b0nbon1** [comment]
I'm also facing the same issue

**Comment by csalmeida** [comment]
Facing the same issue, the goal for me is to build the project and copy it over to a server over SCP.
I have a `build` folder with the theme files here:

```yaml
    - name: Copying project to build folder
      run:  |
        mkdir ../build
        cp -R project/* ../build
```

Files copy sucessfully and the build steps run but when running 

```yaml
    - name: SCP Tasks
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "../build/file.txt"
```

It fails with the following output:

```bash
tar: empty archive
tar all files into /tmp/1620337339/TtFulAUgyu.tar
exit status 1
```

Any tips on how to get past this would be really appreciated. 🙏

**Comment by csalmeida** [comment]
Actually it was my `target` path that was wrong.

For example, if you would like to copy files to `var/www` and you type `var/www/project` you'll actually get the files copied to `var/www/var/www/project`. Changing the target to `project` worked.

**Comment by kasperostberg** [comment]
I have the same issue, doesn't even work when I boil it down to a simple test.txt file:
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          passphrase: ''
          key: ${{ secrets.SSH_KEY }}
          target: ${{ secrets.REMOTE_FOLDER }}
          source: "test.txt"

**Comment by daniel-butler** [comment]
My issue was the source was not where I specified. I had an action create three .envs in a directory. They were not being created in the expected place. Once I updated to where the files actually were this scp action worked!

Try adding a debug command to see what is actually in the source(s) being copied over

```
      - name: List files
        run: ls <optionally add a path> -a
        shell: bash
```

**Comment by appleboy** [comment]
@mkhotib20 `target` must be a directory not a single file path.

**Comment by hendisantika** [comment]
I already do like this but still error:
```
      - name: Upload app-artifacts to remote folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          #          source: ${{ github.sha }}.tar.gz
          source: "app-artifacts.zip"
          target: "/var/www/portofolio/public/"
          strip_components: 1
```

Still got same error:
```
Run appleboy/scp-action@master
/usr/bin/docker run --name e0a46bc0e3976df7454b7cbe3562e3ba988bcf_b843a1 --label e0a46b --workdir /github/workspace --rm -e "INPUT_HOST" -e "INPUT_USERNAME" -e "INPUT_PORT" -e "INPUT_KEY" -e "INPUT_SOURCE" -e "INPUT_TARGET" -e "INPUT_STRIP_COMPONENTS" -e "INPUT_PASSWORD" -e "INPUT_TIMEOUT" -e "INPUT_COMMAND_TIMEOUT" -e "INPUT_KEY_PATH" -e "INPUT_PASSPHRASE" -e "INPUT_FINGERPRINT" -e "INPUT_USE_INSECURE_CIPHER" -e "INPUT_RM" -e "INPUT_DEBUG" -e "INPUT_OVERWRITE" -e "INPUT_TAR_DEREFERENCE" -e "INPUT_TAR_TMP_PATH" -e "INPUT_TAR_EXEC" -e "INPUT_PROXY_HOST" -e "INPUT_PROXY_PORT" -e "INPUT_PROXY_USERNAME" -e "INPUT_PROXY_PASSWORD" -e "INPUT_PROXY_PASSPHRASE" -e "INPUT_PROXY_TIMEOUT" -e "INPUT_PROXY_KEY" -e "INPUT_PROXY_KEY_PATH" -e "INPUT_PROXY_FINGERPRINT" -e "INPUT_PROXY_USE_INSECURE_CIPHER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/portofolio/portofolio":"/github/workspace" e0a46b:c0e3976df7454b7cbe3562e3ba988bcf
drone-scp version: v1.6.14
tar all files into /tmp/VfwaOAazyU.tar.gz
tar: empty archive
exit status 1
```

**Comment by ra2dd** [comment]
I had the similar problem and the answer from [another issue](https://github.com/appleboy/scp-action/issues/150#issuecomment-2092041584) helped in my case.

This was my job:
```
jobs:
  build:
    ...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: 'compose.prod.yml'
          target: '/home/ubuntu'
          port: 22
```
It didn't work for me because the job was unaware about files in the repo. Repo code needed to be checked out in a job even if it was checked out in the previous job.

After correction:
```
jobs:
  build:
    ...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Added code to check out repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: 'compose.prod.yml'
          target: '/home/ubuntu'
          port: 22
```
