### ISSUE TITLE
Exclude Is not added

### ISSUE THREAD

**Issue by expertvillagemed** [appleboy/scp-action#75]
Although the SCP works great but in case you have to exclude some file then this function is not available. I hoping that this will introduce in latest version

**Comment by loekwetzels** [comment]
See #31

**Comment by appleboy** [comment]
@expertvillagemed Post your config?

**Comment by appleboy** [comment]
Solution sample code:

```yaml
  uses: appleboy/scp-action@master
  with:
    host: "example.com"
    username: foo
    password: bar
    port: 22
-   source: "tests/*.txt"
+   source: "tests/*.txt,!tests/a.txt,!tests/b.txt"
    target: "test"
```
