### ISSUE TITLE
drone-scp error:  error copy file to dest: ***, error message: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by simon2022** [appleboy/scp-action#77]
The script sometimes throws this error:

`drone-scp error:  error copy file to dest: ***, error message: wait: remote command exited without exit status or exit signal`

It doesn't always happen, sometimes it works.
The /root path of the target server also contains the .tar file.

**Comment by gizeasy** [comment]
Same problem.
I noticed that the archive appears on the server, its size is 0.
Execution of the script takes about 15 minutes, after which the above error occurs.

Can you suggest where to dig?

**Comment by allandiego** [comment]
im having same issue, in my case if the target folder already got the files in the tar archive the error appears, creating a new empty folder for the upload works without error i think its something related with replace files?

**Comment by kapoko** [comment]
Thanks @allandiego for pointing me in the right direction. Adding
```yaml
overwrite: true
```
seems to help me.

**Comment by mstaudt** [comment]
I also got this issue, turns out it occurs when you're in the directory you're trying to copy to on the server! Make sure to close your SSH connections to the target or navigate to some other directory.

**Comment by Deitsch** [comment]
Also getting this very often, any ideas? :/

**Comment by vinicioslc** [comment]
Hi people !
I have this error when my HD has the space completely full erase all tmp and junks stop show this message

**Comment by Elikill58** [comment]
Hi,
I'm getting same issue. It works 50% of time: each fail need to be run again to make it works.
The disk is used at 66%.

**Comment by premdasvm** [comment]
i'm having the same issue, it works sometime. Anyone came up with a solution for this?

**Comment by josbroers** [comment]
> i'm having the same issue, it works sometime. Anyone came up with a solution for this?

I also changed my server to one with newer hardware and it fixed the problem. I'm using the following config:

```yml
env:
  BUILD_NAME: "${{ github.RUN_ID }}_${{ github.RUN_NUMBER }}"
  BUILD_NAME_EXT: "${{ github.RUN_ID }}_${{ github.RUN_NUMBER }}.tar.gz"

on:
  workflow_call:
    inputs:
      PROJECT_PATH:
        type: string
        required: true
      HOST:
        type: string
        required: true
      USERNAME:
        type: string
        required: true
    secrets:
      KEY:
        required: true

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ inputs.HOST }}
          username: ${{ inputs.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ${{ env.BUILD_NAME_EXT }}
          target: ${{ inputs.PROJECT_PATH }}
          overwrite: true
          timeout: 1m
```
