### ISSUE TITLE
Rename output file

### ISSUE THREAD

**Issue by yusufmalikul** [appleboy/scp-action#84]
Hi, thank you for creating this action.
I want to rename the target file name. In SCP it looks like this:
```
scp ./bin me@server.com:/home/me/bin.new
```

How to do this?

**Comment by GinaCha** [comment]
Hi yusufmalikul,
I had the same issue, the workaround that I used to easily bypass it, was including a step before the scp like below:

```yml
name: Rename and SCP file
on: [push]

jobs:
  rename-and-scp:
    runs-on: ubuntu-latest
    steps:
      - name: Rename file
        run: mv /path/to/local/filename /path/to/local/new_filename
      - name: Copy file using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: /path/to/local/new_name.txt
          target: /path/to/remote/directory/new_name.txt
```
