### ISSUE TITLE
Use password and key at same time

### ISSUE THREAD

**Issue by zploited** [appleboy/scp-action#86]
Hi,
To upload files/connect via ssh my provider requires both password AND private key to authenticate.
If I set both in yml, then I get the error: can't set password and key at the same time

is there something I can do to get around this?

**Comment by appleboy** [comment]
@zploited I will take it.

**Comment by appleboy** [comment]
Some testing:

```yaml
    - name: correct key but wrong password
      uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        password: abcdefg
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"

    - name: correct password but wrong key
      uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: abcdefg
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"
```
