### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey]

### ISSUE THREAD

**Issue by PsclDev** [appleboy/scp-action#88]
My pipeline fails and it throws the message of the title. 

I checked the readme and also read about the supported algorithms.
My key is using `ed25519` algorithm.
If I am trying to run the scp command locally on my machine it is working:
`scp -r -i file srcDir user@host:rootDir`

Dont know why it throws me that issue when everything seems to me right at the moment.

My yml is quite simple and all secrets are set:
```yml
name: publish

on: push

jobs:
  update:
   runs-on: ubuntu-latest
   name: Update

   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Publish
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WWW_HOST }}
        username: ${{ secrets.WWW_HOST_USER }}
        key: ${{ secrets.WWW_HOST_KEY }}
        port: ${{ secrets.WWW_HOST_PORT }}
        source: "./www/*"
        target: ${{ secrets.WWW_HOST_DIR }}
```
