### ISSUE TITLE
drone-scp error:  Process exited with status 1

### ISSUE THREAD

**Issue by Xwilarg** [appleboy/scp-action#95]
Hey,
I'm trying to use scp-action but I'm getting `drone-scp error:  Process exited with status 1`
Step in workflow file:
```
- name: Deploy
  uses: appleboy/scp-action@master
  env:
    HOST: ${{ secrets.DEPLOY_HOST }}
    USERNAME: ${{ secrets.DEPLOY_USER }}
    PORT: 22
    KEY: ${{ secrets.DEPLOY_SSHKEY }}
  with:
    source: "css/,data/,img/,js/,templates/,index.php"
    target: ${{ env.DEPLOY_TARGET }}
```
GitHub action output:
```
tar all files into /tmp/XXXX/XXXX.tar
scp file to server.
create folder 
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file XXXX.tar
2023/01/08 20:14:01 Process exited with status 1
```
