### ISSUE TITLE
Using different ports for multiple hosts

### ISSUE THREAD

**Issue by moshem-pangea** [appleboy/scp-action#98]
Is it possible to use different ports when defining multiple hosts, similar to what you have in [ssh-action](https://github.com/appleboy/ssh-action#multiple-hosts-with-different-port)?
Attempt to define port next to the host, like ```host: "foo.com:5022,bar.com:5122"``` fails.

**Comment by appleboy** [comment]
@moshem-pangea I will take it.

**Comment by appleboy** [comment]
```yaml
    - name: copy file to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}:${{ secrets.PORT }},${{ secrets.HOST }}:${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 1024
        source: tests/a.txt,tests/b.txt
        target: foobar
```

You can ignore the `port` of the setting.
